[phases.setup]
cmds = [
  "apt-get update",
  "apt-get install -y wget gnupg ca-certificates",
  "wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -",
  "sh -c 'echo \"deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main\" >> /etc/apt/sources.list.d/google.list'",
  "apt-get update",
  "apt-get install -y google-chrome-stable xvfb fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf libxss1 --no-install-recommends",
  "rm -rf /var/lib/apt/lists/*"
]

[phases.install]
cmds = ["npm install"]

[start]
cmd = "Xvfb :99 -ac & export DISPLAY=:99 && node main.js"
